basePath: /
host: localhost:8082
info:
  contact: {}
  description: This is a sample server.
  title: Example API
  version: "1.0"
paths:
  /url:
    get:
      consumes:
      - application/json
      description: выполняет сложение двух чисел
      parameters:
      - description: Число 1
        in: query
        name: num1
        required: true
        type: integer
      - description: Число 2
        in: query
        name: num2
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Суммирование двух чисел
      tags:
      - example
swagger: "2.0"
